const randomSentences = [
    "The sun sets on the horizon, casting a warm glow over the tranquil lake and painting the sky in hues of orange and pink.",
    "In the bustling city, people hurry past each other, their lives intertwined in a dance of purpose and ambition.",
    "Lost in the pages of a book, she finds solace in the imaginary worlds and characters that come to life with every word.",
    "The sound of laughter fills the air as friends gather around a crackling bonfire, sharing stories and creating lasting memories.",
    "Through the misty morning fog, a majestic mountain peak emerges, beckoning adventurers to conquer its challenging slopes.",
    "In the vastness of space, stars twinkle like distant diamonds, revealing the beauty and mystery of the universe.",
    "With a paintbrush in hand, the artist brings a blank canvas to life, expressing emotions and visions in vibrant colors.",
    "Amidst the whispering trees, a hidden waterfall cascades down moss-covered rocks, a secret oasis untouched by time.",
    "In the busy marketplace, vendors proudly display their goods, enticing passersby with the sights and scents of their wares.",
    "Beneath a canopy of stars, the campfire crackles, providing warmth and comfort as stories are shared under the night sky.",
    "As the first rays of dawn appear, the sleepy town wakes up to the chirping of birds and the promise of a new day.",
    "On a sandy beach, children build sandcastles while seagulls glide gracefully overhead, carried by the gentle sea breeze.",
    "In the heart of the forest, a babbling brook flows, its crystal-clear waters teeming with life and reflecting the surrounding greenery.",
    "High up in the mountains, a lone wolf howls at the moon, its haunting cry echoing through the silent wilderness.",
    "In the kitchen, the aroma of freshly baked bread fills the air, a comforting scent that brings back memories of home.",
    "Underneath a blanket of snow, the world transforms into a winter wonderland, inviting playful snowball fights and sledding adventures.",
    "In the quaint village, colorful houses line the cobblestone streets, creating a picturesque scene straight out of a postcard.",
    "With a telescope in hand, stargazers observe distant galaxies, marveling at the vastness and complexity of the cosmos.",
    "In the music-filled auditorium, the orchestra plays in harmony, their passionate melodies captivating the audience.",
    "On a lazy afternoon, the gentle rustling of leaves lulls one into a state of peaceful contemplation.",
    "In the fields of golden wheat, farmers toil under the sun, reaping the rewards of their hard work at harvest time.",
    "In a hidden cave, ancient symbols adorn the walls, telling tales of civilizations long gone and forgotten.",
    "Beneath the city lights, a couple dances to the rhythm of the city, their laughter blending with the sounds of the streets.",
    "In the classroom, eager students absorb knowledge like sponges, their curiosity fueling their quest for understanding.",
    "On a distant planet, alien life forms thrive in environments beyond our imagination, evolving in extraordinary ways.",
    "In the bustling cafe, the aroma of freshly brewed coffee envelops patrons, creating a comforting atmosphere of camaraderie.",
    "Amidst a field of wildflowers, butterflies flutter, painting the landscape with vibrant splashes of color.",
    "In the heart of the rainforest, the call of exotic birds fills the air, creating a symphony of nature's finest melodies.",
    "On a summer's day, children run through sprinklers, their laughter echoing through the neighborhood.",
    "In a faraway castle, a princess dreams of adventure, longing to break free from her gilded cage.",
    "Under the starry night sky, astronomers search for distant planets, wondering if life exists beyond our world.",
    "In the quaint bakery, the pastry chef crafts delicate treats, each one a masterpiece of sweetness and flavor.",
    "In the artist's studio, canvases of all sizes hold stories waiting to be told through strokes of paint.",
    "On the edge of a cliff, the brave leap into the abyss, feeling the rush of adrenaline and freedom.",
    "In the old library, the musty scent of aged books transports readers to different eras and far-off lands.",
    "Amidst rolling hills, herds of wild horses roam freely, their untamed spirits a symbol of untamed freedom.",
    "In the grand theater, the curtains rise, revealing a world of enchantment and wonder on the stage.",
    "By the riverside, families enjoy picnics, the water gently flowing by, carrying dreams to distant shores.",
    "In the candlelit room, shadows dance on the walls, creating an atmosphere of mystery and intrigue.",
    "Among ancient ruins, archaeologists piece together the puzzle of the past, unlocking forgotten histories.",
    "In the bustling market, exotic spices fill the air, their alluring scents enticing passersby to explore.",
    "Beneath the moon's glow, a lone wolf howls, its call a haunting reminder of nature's untamed beauty.",
    "On a stormy night, lightning illuminates the dark skies, revealing the raw power of nature's fury.",
    "In the dojo, martial artists train diligently, honing their skills and mastering the art of discipline.",
    "Amidst the cherry blossoms, couples stroll hand in hand, embracing the fleeting beauty of the season.",
    "On a hot summer's day, the ice cream truck's jingle brings joy to children eager for a sweet treat.",
    "In the realm of dreams, imagination knows no bounds, taking us on fantastical adventures while we sleep.",
    "Beneath the ocean's surface, a coral reef thrives, housing a myriad of colorful creatures in a delicate ecosystem.",
    "In the enchanted forest, fairies flit about, leaving traces of magic wherever they go.",
    "Among ancient ruins, the whispers of the past echo through time, sharing tales of civilizations long gone.",
    "In the secluded garden, the fragrance of blooming flowers fills the air, a symphony of scents that delights the senses.",
    "Under the city lights, musicians gather to play, their melodies weaving through the urban landscape.",
    "In the rolling meadows, a farmer tends to a herd of contented cows, their soft moos filling the countryside.",
    "In the charming cottage, a crackling fireplace warms the room, providing comfort on chilly winter nights.",
    "On the vibrant city streets, street artists create masterpieces that captivate and inspire passersby.",
    "Amidst ancient temples, monks meditate in serene silence, seeking enlightenment and inner peace.",
    "In the bustling harbor, ships from distant lands dock, bringing with them stories of adventure and discovery.",
    "Under the starlit sky, friends gather around a campfire, sharing tales that ignite the imagination.",
    "In the open savannah, a lioness leads her pride, a symbol of strength and unity in the animal kingdom.",
    "On a rainy afternoon, the pitter-patter of raindrops creates a soothing melody, inviting a cozy day indoors.",
]
  
module.exports = randomSentences